// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO "order" (
    id,
    "userId",
    total
) VALUES (
    $1, $2, $3
) RETURNING id, "userId", total, status, "createdAt", "updatedAt"
`

type CreateOrderParams struct {
	ID     uuid.UUID `json:"id"`
	UserId uuid.UUID `json:"userId"`
	Total  float64   `json:"total"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.ID, arg.UserId, arg.Total)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Total,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllOrderByUserId = `-- name: GetAllOrderByUserId :one
SELECT id, "userId", total, status, "createdAt", "updatedAt" FROM "order"
WHERE "userId" = $1
`

func (q *Queries) GetAllOrderByUserId(ctx context.Context, userid uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getAllOrderByUserId, userid)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Total,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllOrderItem = `-- name: GetAllOrderItem :many
SELECT id, "orderId", "productId", quantity, price, "createdAt", "updatedAt" FROM "orderItem"
WHERE "orderId" = $1
`

func (q *Queries) GetAllOrderItem(ctx context.Context, orderid uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getAllOrderItem, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderId,
			&i.ProductId,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, "userId", total, status, "createdAt", "updatedAt" FROM "order"
WHERE id = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Total,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
