// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: product.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO "product" (
    id,
    name,
    description,
    price,
    stock,
    "createdBy"
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, description, price, stock, "createdAt", "updatedAt", "createdBy"
`

type CreateProductParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       float64   `json:"price"`
	Stock       int32     `json:"stock"`
	CreatedBy   uuid.UUID `json:"createdBy"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.CreatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteOneProduct = `-- name: DeleteOneProduct :exec
DELETE FROM product
WHERE id = $1
`

func (q *Queries) DeleteOneProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOneProduct, id)
	return err
}

const getAllProduct = `-- name: GetAllProduct :many
SELECT
    id,
    name,
    description,
    price,
    stock,
    "createdBy",
    "createdAt",
    "updatedAt"
FROM "product"
`

type GetAllProductRow struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Price       float64          `json:"price"`
	Stock       int32            `json:"stock"`
	CreatedBy   uuid.UUID        `json:"createdBy"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

func (q *Queries) GetAllProduct(ctx context.Context) ([]GetAllProductRow, error) {
	rows, err := q.db.Query(ctx, getAllProduct)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllProductRow{}
	for rows.Next() {
		var i GetAllProductRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMultipleProductById = `-- name: GetMultipleProductById :many
SELECT
    id,
    price,
    stock
FROM product
WHERE id = ANY($1::UUID[])
`

type GetMultipleProductByIdRow struct {
	ID    uuid.UUID `json:"id"`
	Price float64   `json:"price"`
	Stock int32     `json:"stock"`
}

func (q *Queries) GetMultipleProductById(ctx context.Context, dollar_1 []uuid.UUID) ([]GetMultipleProductByIdRow, error) {
	rows, err := q.db.Query(ctx, getMultipleProductById, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMultipleProductByIdRow{}
	for rows.Next() {
		var i GetMultipleProductByIdRow
		if err := rows.Scan(&i.ID, &i.Price, &i.Stock); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneProduct = `-- name: GetOneProduct :one
SELECT
    id,
    name,
    description,
    price,
    stock,
    "createdBy",
    "createdAt",
    "updatedAt"
FROM "product"
WHERE id = $1
LIMIT 1
`

type GetOneProductRow struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Price       float64          `json:"price"`
	Stock       int32            `json:"stock"`
	CreatedBy   uuid.UUID        `json:"createdBy"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

func (q *Queries) GetOneProduct(ctx context.Context, id uuid.UUID) (GetOneProductRow, error) {
	row := q.db.QueryRow(ctx, getOneProduct, id)
	var i GetOneProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOneProduct = `-- name: UpdateOneProduct :one
UPDATE product
SET
    name = $1,
    description = $2,
    price = $3,
    stock = $4,
    updated_at = NOW()
WHERE id = $5
RETURNING id, name, description, price, stock, "createdAt", "updatedAt", "createdBy"
`

type UpdateOneProductParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       float64   `json:"price"`
	Stock       int32     `json:"stock"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateOneProduct(ctx context.Context, arg UpdateOneProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateOneProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE product
SET
    stock = stock - $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, price, stock, "createdAt", "updatedAt", "createdBy"
`

type UpdateProductStockParams struct {
	ID    uuid.UUID `json:"id"`
	Stock int32     `json:"stock"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
