// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOneProduct(ctx context.Context, id uuid.UUID) error
	GetAllProduct(ctx context.Context) ([]GetAllProductRow, error)
	GetOneProduct(ctx context.Context, id uuid.UUID) (GetOneProductRow, error)
	GetUserById(ctx context.Context, email string) (GetUserByIdRow, error)
}

var _ Querier = (*Queries)(nil)
